version: '3'

services:
  mysql:
    container_name: payhere-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "payhere"
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    ports:
      - '3306:3306'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    restart: always

  redis:
    container_name: payhere-redis
    image: redis
    restart: always
    ports:
      - '6379:6379'