spring:
  config:
    import:
      - application-redis.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/payhere?useSSL=false&serverTimezone=Asia/Seoul

logging:
  level:
    org.hibernate.type.descriptor.sql: trace